runtime ./modules/plugins.vim
runtime ./modules/settings.vim
runtime ./modules/telescope.vim
runtime ./modules/mappings.vim
runtime ./modules/lsp.vim
runtime ./modules/tree-sitter.vim
runtime ./modules/yoink.vim
runtime ./modules/which-key.vim
runtime ./modules/autopairs.vim
runtime ./user.vim
